title: "Simon AZAR"
description: >- # this means to ignore newlines until "baseurl:"
  I am an engineer passionate about understanding and fixing things. In this blog, I share with you what I figured out. 

url: "https://simazar.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#author: "Simon AZAR"
timezone: France
show_excerpts: true
permalink: /:categories/:title

# Header links
header_pages: 
  - posts.markdown
  - index.markdown

# Social
github_username: simazar
linkedin_username: simazar

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  #- jekyll-sitemap
  #- jekyll-redirect-from
  #- jekyll-seo-tag

defaults:
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post
      comments: false