title: "Simon AZAR"
description: >- # this means to ignore newlines until "baseurl:"
  I am a computer science engineer. I share things I learned and that I find interesting.
url: "https://simazar.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author: "Simon AZAR"
timezone: France
show_excerpts: true
permalink: /:categories/:title

# Header links
header_pages: 
  - [LinkedIn](https://www.linkedin.com/in/azarsimon/)
  - subscriptions.md
  - blogs.md

# Social
github_username: simazar
linkedin_username: simonazar

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag

defaults:
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post
      comments: false
